<?php
/**
 * phpMyAdmin configuration for production environment
 * Generated by siimut-image-docker
 */

/* Servers configuration */
$i = 0;

/* Server: MariaDB via Docker */
$i++;
$cfg['Servers'][$i]['host'] = 'db';
$cfg['Servers'][$i]['port'] = '3306';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = '';
$cfg['Servers'][$i]['password'] = '';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['AllowNoPassword'] = false;

/* Production Security Settings */
$cfg['blowfish_secret'] = getenv('PMA_BLOWFISH_SECRET') ?: 'siimut-production-secret-key-change-in-production-2024';
$cfg['VersionCheck'] = false;
$cfg['SendErrorReports'] = 'never';
$cfg['CheckConfigurationPermissions'] = true;

/* Performance & Limits */
$cfg['ExecTimeLimit'] = 600;
$cfg['MemoryLimit'] = '1024M';
$cfg['MaxRows'] = 500;
$cfg['RowActionLinksWithoutUnique'] = false;

/* Session Configuration */
$cfg['SessionSavePath'] = '/sessions';
$cfg['LoginCookieValidity'] = 3600; // 1 hour
$cfg['LoginCookieRecall'] = false;
$cfg['LoginCookieDeleteAll'] = true;

/* Security Features */
$cfg['CaptchaLoginPrivateKey'] = '';
$cfg['CaptchaLoginPublicKey'] = '';
$cfg['AllowThirdPartyFraming'] = false;
$cfg['CSPAllow'] = '';

/* Export/Import Limits */
$cfg['ExportLimitRows'] = 100000;
$cfg['ImportMaxFileSize'] = '1024M';
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';

/* UI Configuration */
$cfg['DefaultLang'] = 'en';
$cfg['ThemeDefault'] = 'pmahomme';
$cfg['NavigationTreeDisplayItemFilterMinimum'] = 30;
$cfg['NumRecentTables'] = 10;
$cfg['NumFavoriteTables'] = 10;

/* SQL Configuration */
$cfg['SQLQuery']['Edit'] = true;
$cfg['SQLQuery']['Explain'] = true;
$cfg['SQLQuery']['ShowAsPHP'] = true;
$cfg['SQLQuery']['Refresh'] = true;

/* Logging */
$cfg['Error_Handler']['display'] = false;
$cfg['Error_Handler']['gather'] = true;

/* Disable potentially dangerous features for production */
$cfg['ShowServerInfo'] = false;
$cfg['ShowPhpInfo'] = false;
$cfg['ShowChgPassword'] = false;
$cfg['ShowCreateDb'] = false;
$cfg['SuhosinDisableWarning'] = true;

/* Designer */
$cfg['Designer']['DefaultTabConf'] = array(
    'query' => true,
    'structure' => true,
    'sql' => true,
    'search' => true,
    'browse' => true,
    'empty' => true,
    'drop' => true,
);

/* Console */
$cfg['Console']['StartHistory'] = false;
$cfg['Console']['AlwaysExpand'] = false;
$cfg['Console']['Height'] = 92;

/* End of servers configuration */
?>