#!/bin/bash

echo "=========================================="
echo "IAM SSO QUICK DIAGNOSTICS"
echo "=========================================="
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${YELLOW}1. IAM CONTAINER CONFIG${NC}"
docker compose -f docker-compose-multi-apps.yml exec -T app-iam php -r "
require 'vendor/autoload.php';
\$app = require 'bootstrap/app.php';
\$app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();
echo 'APP_URL: ' . config('app.url') . PHP_EOL;
echo 'IAM_ISSUER: ' . config('iam.issuer') . PHP_EOL;
" 2>&1
echo ""

echo -e "${YELLOW}2. SIIMUT CONTAINER CONFIG${NC}"
docker compose -f docker-compose-multi-apps.yml exec -T app-siimut php -r "
require 'vendor/autoload.php';
\$app = require 'bootstrap/app.php';
\$app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();
echo 'APP_URL: ' . config('app.url') . PHP_EOL;
echo 'IAM_ISSUER (expect): ' . config('iam.issuer') . PHP_EOL;
echo 'IAM_HOST: ' . config('iam.host') . PHP_EOL;
" 2>&1
echo ""

echo -e "${YELLOW}3. ENV FILE (.env.iam)${NC}"
grep -E "^APP_URL|^IAM_ISSUER|^TRUSTED_PROXIES" env/.env.iam
echo ""

echo -e "${YELLOW}4. DOCKER COMPOSE ENV OVERRIDE (app-iam section)${NC}"
grep -A 30 "app-iam:" docker-compose-multi-apps.yml | grep -E "environment:|APP_URL|IAM_ISSUER" | head -10
echo ""

echo -e "${YELLOW}5. CHECK: Do configs MATCH?${NC}"
IAM_CONFIG=$(docker compose -f docker-compose-multi-apps.yml exec -T app-iam php -r "
require 'vendor/autoload.php';
\$app = require 'bootstrap/app.php';
\$app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();
echo config('iam.issuer');
" 2>&1)

SIIMUT_CONFIG=$(docker compose -f docker-compose-multi-apps.yml exec -T app-siimut php -r "
require 'vendor/autoload.php';
\$app = require 'bootstrap/app.php';
\$app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();
echo config('iam.issuer');
" 2>&1)

echo "IAM generates token with iss: $IAM_CONFIG"
echo "SIIMUT expects iss: $SIIMUT_CONFIG"

if [ "$IAM_CONFIG" = "$SIIMUT_CONFIG" ]; then
    echo -e "${GREEN}✓ ISSUER MATCH - Token verification should work${NC}"
else
    echo -e "${RED}✗ ISSUER MISMATCH - This causes signature verification to fail!${NC}"
fi
echo ""

echo -e "${YELLOW}6. QUICK STATUS${NC}"
echo "Server status:"
curl -s -o /dev/null -w "IAM: %{http_code}\n" http://127.0.0.1:8100/health
curl -s -o /dev/null -w "SIIMUT: %{http_code}\n" http://127.0.0.1:8000/health
echo ""

echo -e "${YELLOW}=== PROBLEM DIAGNOSIS ===${NC}"
echo "If ISSUER MISMATCH appears above, the issue is:"
echo "❌ Token generated by IAM has wrong iss claim"
echo "❌ SIIMUT cannot verify signature - session invalid"
echo "❌ Browser redirected back to login - LOOP"
echo ""
echo "Solution: Ensure docker-compose environment override really works"
echo ""
